//! Grader namespace and shared grader model types.

use std::collections::HashMap;

use crate::Client;

/// Graders service root.
#[derive(Clone)]
pub struct GraderService {
    client: Client,
}

impl GraderService {
    pub(crate) fn new(client: Client) -> Self {
        Self { client }
    }

    /// Returns the grader model namespace service.
    #[must_use]
    pub fn grader_models(&self) -> GraderModelService {
        GraderModelService::new(self.client.clone())
    }
}

/// Grader model namespace.
#[derive(Clone)]
pub struct GraderModelService {
    client: Client,
}

impl GraderModelService {
    pub(crate) fn new(client: Client) -> Self {
        Self { client }
    }

    /// Returns an immutable reference to the parent client for future request APIs.
    #[must_use]
    pub fn client_ref(&self) -> &Client {
        &self.client
    }
}

/// Input content type used for grading.
#[derive(Debug, Clone, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum GraderInputType {
    /// Plain text input content.
    InputText,
    /// Text output generated by a model.
    OutputText,
    /// Image input content.
    InputImage,
    /// Audio input content.
    InputAudio,
}

/// Grader input payload.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct GraderInput {
    /// Input variant type.
    #[serde(rename = "type")]
    pub input_type: GraderInputType,
    /// Text content when applicable.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub text: Option<String>,
    /// Image URL when `type` is `input_image`.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub image_url: Option<String>,
    /// Detail hint for image inputs (`low`/`high`/`auto`).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub detail: Option<String>,
}

/// One grader evaluation result.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct GraderResult {
    /// Pass/fail outcome.
    pub pass: bool,
    /// Optional numeric score.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub score: Option<f32>,
    /// Optional explanatory rationale.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub rationale: Option<String>,
    /// Free-form provider metadata.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub metadata: Option<HashMap<String, serde_json::Value>>,
}

/// Grader response payload.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct GraderResponse {
    /// Response ID.
    pub id: String,
    /// Object type.
    pub object: String,
    /// Evaluation results.
    pub results: Vec<GraderResult>,
}

#[cfg(test)]
mod tests {
    use super::{GraderInput, GraderInputType, GraderResponse};

    #[test]
    fn grader_input_type_serializes_snake_case() {
        let json = serde_json::to_string(&GraderInputType::OutputText).expect("serialize enum");
        assert_eq!(json, "\"output_text\"");
    }

    #[test]
    fn grader_input_omits_none_fields() {
        let input = GraderInput {
            input_type: GraderInputType::InputText,
            text: Some("hello".to_owned()),
            image_url: None,
            detail: None,
        };

        let value = serde_json::to_value(input).expect("serialize grader input");
        assert_eq!(
            value.get("type"),
            Some(&serde_json::Value::String("input_text".to_owned()))
        );
        assert!(value.get("image_url").is_none());
        assert!(value.get("detail").is_none());
    }

    #[test]
    fn grader_response_deserializes_results() {
        let json = r#"{
            "id":"grader_resp_1",
            "object":"grader.response",
            "results":[{"pass":true,"score":0.92,"rationale":"great answer"}]
        }"#;

        let response: GraderResponse =
            serde_json::from_str(json).expect("deserialize grader response");
        assert_eq!(response.results.len(), 1);
        assert!(response.results[0].pass);
    }
}
